export const PATHS = {
    HOME: '/',
    PROFILE: '/profile',
    CONTACT_INFO: 'contact-info',
    PROFILE_CONTACT_INFO: '/profile/contact-info',
    PROFILE_ORDERS: '/profile/orders',
    ORDERS: 'orders',
    BASKET: '/basket',
    CATALOG: '/catalog',
    SINGLE_PRODUCT: 'single-product/:id',
    CREATE_ORDER: '/create-order',
    SIGN_UP: '/signup',
    LOGIN: '/login',
    CONTACT: '/contact',
    ABOUT: '/about',
    UNEXPECTED_PATHS: '*',

    ADMIN_USERS: '/profile/admin/users',
    ADMIN_CATEGORIES: '/profile/admin/categories',
    ADMIN_PRODUCTS: '/profile/admin/products',
    ADMIN_ORDERS: '/profile/admin/orders',
};